"""x402 payment middleware for MCP tool calls.

Intercepts POST /mcp requests at the ASGI level. Methods other than
tools/call (initialize, tools/list, ping, etc.) pass through free.
For tools/call:
  - No X-PAYMENT header → 402 with X-PAYMENT-REQUIRED header + body
  - Valid X-PAYMENT header → verify → forward → settle → X-PAYMENT-RESPONSE

Settlement happens after the downstream response is confirmed non-error
(status < 400), with a 10s timeout so a slow facilitator can't hang the
connection. CORS headers are added to all error responses because this
middleware is outermost and would otherwise bypass CORSMiddleware.

Uses pure ASGI middleware (not BaseHTTPMiddleware) to avoid body-consume
issues — we buffer the receive stream ourselves and replay it downstream.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os

from starlette.responses import JSONResponse
from starlette.types import ASGIApp, Receive, Scope, Send
from x402.http.utils import (
    decode_payment_signature_header,
    encode_payment_required_header,
    encode_payment_response_header,
)
from x402.schemas.config import ResourceConfig

logger = logging.getLogger(__name__)

_MAX_BODY = 1 * 1024 * 1024  # 1 MB — MCP JSON-RPC is tiny; cap for DoS safety
_SETTLE_TIMEOUT = 10.0       # seconds — don't let a slow facilitator hang the send channel

# Per-tool prices — must match build_route_configs() in payments.py
_TOOL_PRICES: dict[str, str] = {
    "qr_generate": "$0.001",
    "dns_health": "$0.003",
    "email_validate": "$0.005",
    "ip_lookup": "$0.005",
    "url_health": "$0.003",
    "whois_lookup": "$0.005",
    "headers_analyze": "$0.003",
    "extract_text": "$0.005",
    "tech_detect": "$0.005",
}

# MCP methods that don't require payment
_FREE_METHODS = frozenset({
    "initialize",
    "tools/list",
    "ping",
    "notifications/initialized",
    "notifications/cancelled",
    "$/cancelRequest",
    "resources/list",
    "resources/read",
    "prompts/list",
    "prompts/get",
    "completion/complete",
})

# CORS headers added to all responses generated by this middleware.
# Because MCPPaymentMiddleware is outermost, error responses bypass
# CORSMiddleware — so we set Allow-Origin here manually.
_CORS_HEADERS = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "*",
    "Access-Control-Expose-Headers": "X-PAYMENT-REQUIRED, X-PAYMENT-RESPONSE",
}


def _error_response(message: str, status: int = 402) -> JSONResponse:
    return JSONResponse(content={"error": message}, status_code=status, headers=_CORS_HEADERS)


class MCPPaymentMiddleware:
    """x402 payment gate for MCP tools/call requests.

    Mounts on the FastAPI app before FastMCP's /mcp mount. Only POST requests
    to /mcp or /mcp/ are inspected; all other paths pass through immediately.
    """

    def __init__(self, app: ASGIApp, *, server, testnet: bool = False) -> None:
        self.app = app
        self._server = server
        self._testnet = testnet
        self._init_done = False
        self._init_lock = asyncio.Lock()

    async def _ensure_initialized(self) -> None:
        """Lazy-initialize the x402 server (fetches /supported from facilitator)."""
        if not self._init_done:
            async with self._init_lock:
                if not self._init_done:
                    await asyncio.to_thread(self._server.initialize)
                    self._init_done = True

    def _build_requirements(self, price: str) -> list:
        pay_to = os.environ.get("AGENT_TOOLS_PAY_TO", "")
        if not pay_to:
            raise RuntimeError("AGENT_TOOLS_PAY_TO is not set — cannot build payment requirements")
        network = "eip155:84532" if self._testnet else "eip155:8453"
        config = ResourceConfig(
            scheme="exact",
            pay_to=pay_to,
            price=price,
            network=network,
            max_timeout_seconds=300,
        )
        return self._server.build_payment_requirements(config)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        path: str = scope["path"]
        method: str = scope.get("method", "")

        if method != "POST" or path not in ("/mcp", "/mcp/"):
            await self.app(scope, receive, send)
            return

        # Buffer the full body (may arrive in chunks); cap at 1 MB
        body = b""
        more_body = True
        while more_body:
            message = await receive()
            body += message.get("body", b"")
            more_body = message.get("more_body", False)
            if len(body) > _MAX_BODY:
                await _error_response("Request body too large", 413)(scope, receive, send)
                return

        # Replay callable for downstream — lets FastMCP read the body after us
        async def replay() -> dict:
            return {"type": "http.request", "body": body, "more_body": False}

        # Parse MCP method
        try:
            data: dict = json.loads(body) if body else {}
        except (json.JSONDecodeError, ValueError):
            await self.app(scope, replay, send)
            return

        mcp_method: str = data.get("method", "")

        # Everything except tools/call passes free
        if mcp_method != "tools/call":
            await self.app(scope, replay, send)
            return

        # tools/call — payment required
        tool_name: str = (data.get("params") or {}).get("name", "unknown")
        price: str = _TOOL_PRICES.get(tool_name, "$0.005")

        # Extract X-PAYMENT header from ASGI scope (bytes); reject duplicates
        raw_headers: list[tuple[bytes, bytes]] = scope.get("headers", [])
        payment_values = [v for k, v in raw_headers if k.lower() == b"x-payment"]
        if len(payment_values) > 1:
            err = _error_response("Multiple X-PAYMENT headers are not permitted")
            await err(scope, replay, send)
            return

        try:
            payment_header = payment_values[0].decode("utf-8") if payment_values else ""
        except UnicodeDecodeError:
            await _error_response("Invalid X-PAYMENT header encoding")(scope, replay, send)
            return

        await self._ensure_initialized()
        try:
            requirements = self._build_requirements(price)
        except RuntimeError as exc:
            logger.error("MCP payment config error: %s", exc)
            await _error_response("Payment service misconfigured", 500)(scope, replay, send)
            return

        if not payment_header:
            # Return 402 Payment Required
            payment_required = self._server.create_payment_required_response(requirements)
            pr_json = json.loads(
                payment_required.model_dump_json(by_alias=True, exclude_none=True)
            )
            response = JSONResponse(
                content=pr_json,
                status_code=402,
                headers={
                    **_CORS_HEADERS,
                    "X-PAYMENT-REQUIRED": encode_payment_required_header(payment_required),
                },
            )
            await response(scope, replay, send)
            return

        # Decode and verify the payment
        try:
            payload = decode_payment_signature_header(payment_header)
        except Exception as exc:
            await _error_response(f"Invalid X-PAYMENT header: {exc}")(scope, replay, send)
            return

        # find_matching_requirements resolves list → single PaymentRequirements for verify/settle
        matching = self._server.find_matching_requirements(requirements, payload)
        if matching is None:
            await _error_response("Payment requirements do not match any accepted scheme")(
                scope, replay, send
            )
            return

        verify_response = await self._server.verify_payment(payload, matching)
        if not verify_response.is_valid:
            await _error_response(f"Payment invalid: {verify_response.invalid_reason}")(
                scope, replay, send
            )
            return

        # Payment verified — forward request, settle after non-error response
        async def send_with_settlement(message: dict) -> None:
            if message["type"] == "http.response.start" and message.get("status", 500) < 400:
                try:
                    settle = await asyncio.wait_for(
                        self._server.settle_payment(payload, matching),
                        timeout=_SETTLE_TIMEOUT,
                    )
                    if settle.success:
                        hdrs = list(message.get("headers", []))
                        hdrs.append((
                            b"x-payment-response",
                            encode_payment_response_header(settle).encode("utf-8"),
                        ))
                        message = {**message, "headers": hdrs}
                    else:
                        logger.warning(
                            "MCP payment settlement failed for %s: %s",
                            tool_name, settle.error_reason,
                        )
                except TimeoutError:
                    logger.error(
                        "MCP payment settlement timed out for tool %s after %.0fs",
                        tool_name, _SETTLE_TIMEOUT,
                    )
                except Exception:
                    logger.exception("MCP payment settlement error for tool %s", tool_name)
            await send(message)

        await self.app(scope, replay, send_with_settlement)
